


#forwardCurve is a utility class that is meant to be used together with the spotCurve class.
#
#A forwardCurve object takes in an array of point-estimates for spot curve(s) which has been generated by a spotCurve object.
#Like spotCurve, it assumes the spot curve(s) correspond to consecutive business day(s).
#
#A forwardCurve object is used to create an array of point-estimates for 1-year forward curve(s) by
# generating one forward curve corresponding to each spot curve in the given array of point-estimates for spot curve(s).
#
#It generates point-estimates for the 1-year forward curve for terms range from 2-5 years.
#Like spotCurve, forwardCurve uses linear interpolation to obtain its point-estimates.
	
	

class forwardCurve:	
	
	#Constructor
	def __init__(self, spotArray):
		self.spotArray = spotArray
		self.forwardArray = []		#stores point-estimates for the forward curve(s)
		
	
	#Getter methods:
		
	def getSpotArray(self):
		return self.spotArray

	def getForwardArray(self):
		return self.forwardArray
		
		
		
		
	#Calculate the array of point-estimates for the forward curve(s)
	def calcRates(self):
		numDays = len(self.getSpotArray())
		for i in range(numDays):	#Generate one forward curve corresponding to each spot curve in spotArray
			self.calcRatesIter(i)
		
		
	#Calculate the point-estimates for a forward curve on a given day
	def calcRatesIter(self, day):
		self.forwardArray.append([])
		
		#From spotArray, get the closest points to the yield at time T=1.
		rPrev = self.getSpotArray()[day][1][0]
		rNext = self.getSpotArray()[day][2][0]
		tPrev = self.getSpotArray()[day][1][1]
		tNext = self.getSpotArray()[day][2][1]
		
		r1 = rPrev + (rNext - rPrev)/(tNext - tPrev)*(1-tPrev)	#Estimate the yield at T=1 via linear interpolation.
	
		#Generate point-estimates for each of the 1yr-1yr, 1yr-2yr, 1yr-3yr, and 1yr-4yr forward rates.
		for i in range(1,5):
			#From spotArray, get the closest points to the yield at time T=i+1.
			#Multiplication by 2 is b/c i is in years but there is one point-estimate for every 6 months in spotArray
			rPrev = self.getSpotArray()[day][2*i + 1][0]
			rNext = self.getSpotArray()[day][2*i + 2][0]
			tPrev = self.getSpotArray()[day][2*i + 1][1]
			tNext = self.getSpotArray()[day][2*i + 2][1]

			ri = rPrev + (rNext - rPrev)/(tNext - tPrev)*(i+1-tPrev)	#Estimate the yield at T=i+1 via linear interpolation.
		
			f = (ri*(i+1) - r1)/i	#Calculate the 1yr-iyr forward rate
				
			self.forwardArray[-1].append(f)
			

